# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('help_app', '0003_remove_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='like',
            field=models.ManyToManyField(related_name='liked_jobs', to='login_app.User'),
        ),
    ]
